#!/usr/bin/env bash

# Prepare an isolated DE10-Pro Quartus project. This script does not invoke
# Quartus or program the board.
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
VORTEX_HOME=$(realpath "$SCRIPT_DIR/../../../..")
PCIE_ROOT=$(realpath "$VORTEX_HOME/../PCIE_test")
LEGACY_PROJECT=$PCIE_ROOT/PCIE_DDR4_Vortex
PROJECT_DIR=$PCIE_ROOT/PCIE_DDR4_VortexCrypto
PROJECT_MARKER=$PROJECT_DIR/.vortexcrypto-de10pro-project
NUM_WARPS=${VX_DE10PRO_NUM_WARPS:-1}
NUM_THREADS=${VX_DE10PRO_NUM_THREADS:-1}

if [[ ! "$NUM_WARPS" =~ ^[1-9][0-9]*$ \
   || ! "$NUM_THREADS" =~ ^[1-9][0-9]*$ ]]; then
    echo "error: warp/thread counts must be positive integers" >&2
    exit 1
fi

if [[ ! -f "$LEGACY_PROJECT/DE10_Pro.qsf" \
   || ! -f "$LEGACY_PROJECT/ep_g3x8_avmmdma256_integrated.qsys" \
   || ! -f "$LEGACY_PROJECT/vortex_shell_hw.tcl" ]]; then
    echo "error: incomplete legacy DE10-Pro project: $LEGACY_PROJECT" >&2
    exit 1
fi

if [[ ! -f "$VORTEX_HOME/VX_config.toml" \
   || ! -f "$VORTEX_HOME/VX_types.toml" \
   || ! -f "$VORTEX_HOME/hw/rtl/afu/de10pro/vortex_shell.sv" ]]; then
    echo "error: incomplete vortexCrypto checkout: $VORTEX_HOME" >&2
    exit 1
fi

if [[ -e "$PROJECT_DIR" && ! -f "$PROJECT_MARKER" ]]; then
    echo "error: refusing to overwrite unmarked directory: $PROJECT_DIR" >&2
    exit 1
fi

mkdir -p "$PROJECT_DIR"
touch "$PROJECT_MARKER"

# Keep only the reusable board, Qsys, and generated-IP baseline. Existing
# build results in PROJECT_DIR are intentionally left alone on a refresh.
rsync -a \
    --exclude='/.git/' \
    --exclude='/.codex' \
    --exclude='/.qsys_edit/' \
    --exclude='/db/' \
    --exclude='/qdb/' \
    --exclude='/incremental_db/' \
    --exclude='/output_files/' \
    --exclude='/results/' \
    --exclude='/demo_batch/' \
    --exclude='/tmp-clearbox/' \
    --exclude='/synth_dumps/' \
    --exclude='/ip_upgrade_port_diff_reports/' \
    --exclude='/*.rpt' \
    --exclude='/*.csv' \
    --exclude='/*.sof' \
    "$LEGACY_PROJECT/" "$PROJECT_DIR/"

GENERATED_DIR=$PROJECT_DIR/generated/vortexcrypto
CONFIG_DIR=$GENERATED_DIR/config
FILELIST=$GENERATED_DIR/sources.f
QSF_FRAGMENT=$GENERATED_DIR/vortex_sources.qsf
mkdir -p "$CONFIG_DIR"

CONFIG_FLAGS="-DSYNTHESIS=1 -DQUARTUS=1 -DNDEBUG=1 -DVX_CFG_XLEN=32 -DVX_CFG_XLEN_32=1 -DVX_CFG_NUM_CLUSTERS=1 -DVX_CFG_NUM_CORES=1 -DVX_CFG_NUM_WARPS=$NUM_WARPS -DVX_CFG_NUM_THREADS=$NUM_THREADS -DVX_CFG_EXT_F_DISABLE=1 -DVX_CFG_EXT_D_DISABLE=1 -DVX_CFG_PLATFORM_MEMORY_NUM_BANKS=1 -DVX_CFG_PLATFORM_MEMORY_INTERLEAVE=0"

XLEN=32 python3 "$VORTEX_HOME/ci/gen_config.py" \
    --config "$VORTEX_HOME/VX_config.toml" \
    --cflags "$CONFIG_FLAGS" \
    --format verilog \
    --output "$CONFIG_DIR/VX_config.vh"

XLEN=32 python3 "$VORTEX_HOME/ci/gen_config.py" \
    --config "$VORTEX_HOME/VX_types.toml" \
    --cflags "$CONFIG_FLAGS" \
    --format verilog \
    --resolved \
    --output "$CONFIG_DIR/VX_types.vh"

"$VORTEX_HOME/hw/scripts/gen_sources.sh" \
    -DSYNTHESIS=1 \
    -DQUARTUS=1 \
    -DNDEBUG=1 \
    -DVX_CFG_XLEN=32 \
    -DVX_CFG_XLEN_32=1 \
    -DVX_CFG_NUM_CLUSTERS=1 \
    -DVX_CFG_NUM_CORES=1 \
    -DVX_CFG_NUM_WARPS="$NUM_WARPS" \
    -DVX_CFG_NUM_THREADS="$NUM_THREADS" \
    -DVX_CFG_EXT_F_DISABLE=1 \
    -DVX_CFG_EXT_D_DISABLE=1 \
    -DVX_CFG_PLATFORM_MEMORY_NUM_BANKS=1 \
    -DVX_CFG_PLATFORM_MEMORY_INTERLEAVE=0 \
    -I"$CONFIG_DIR" \
    -I"$VORTEX_HOME/hw/rtl" \
    -I"$VORTEX_HOME/hw/rtl/libs" \
    -I"$VORTEX_HOME/hw/rtl/interfaces" \
    -I"$VORTEX_HOME/hw/rtl/fpu" \
    -I"$VORTEX_HOME/hw/rtl/core" \
    -I"$VORTEX_HOME/hw/rtl/mem" \
    -I"$VORTEX_HOME/hw/rtl/cache" \
    -I"$VORTEX_HOME/hw/rtl/afu/de10pro" \
    -O"$FILELIST"

{
    echo "# Generated by vortexCrypto/hw/syn/altera/de10pro/prepare_project.sh"
    while IFS= read -r entry; do
        case "$entry" in
            +define+*)
                printf 'set_global_assignment -name VERILOG_MACRO "%s"\n' "${entry#+define+}"
                ;;
            +incdir+*)
                printf 'set_global_assignment -name SEARCH_PATH "%s"\n' "${entry#+incdir+}"
                ;;
            *.sv)
                printf 'set_global_assignment -name SYSTEMVERILOG_FILE "%s"\n' "$entry"
                ;;
            *.v)
                printf 'set_global_assignment -name VERILOG_FILE "%s"\n' "$entry"
                ;;
            '') ;;
            *)
                echo "error: unsupported source-list entry: $entry" >&2
                exit 1
                ;;
        esac
    done < "$FILELIST"
} > "$QSF_FRAGMENT"

# Drop the hand-maintained myvortex source list and every legacy feature macro.
# Board pin, timing, Qsys, and IP assignments remain unchanged.
QSF_TMP=$(mktemp "$PROJECT_DIR/DE10_Pro.qsf.XXXXXX")
awk '
    /^[[:space:]]*#?[[:space:]]*set_global_assignment -name VERILOG_MACRO / { next }
    /^[[:space:]]*set_global_assignment -name SEARCH_PATH .*myvortex/ { next }
    /^[[:space:]]*set_global_assignment -name SYSTEMVERILOG_FILE .*myvortex/ { next }
    { print }
' "$PROJECT_DIR/DE10_Pro.qsf" > "$QSF_TMP"
printf '\n# vortexCrypto current-master RTL (RV32, 1 cluster/core, %s warp(s), %s thread(s), F/D disabled, one memory bank)\n' \
    "$NUM_WARPS" "$NUM_THREADS" >> "$QSF_TMP"
cat "$QSF_FRAGMENT" >> "$QSF_TMP"
mv "$QSF_TMP" "$PROJECT_DIR/DE10_Pro.qsf"

# Qsys component discovery and the cached synthesis copy must agree. The
# project deliberately keeps IP regeneration disabled to preserve the tested
# PCIe/DDR4 shell.
TCL_TMP=$(mktemp "$PROJECT_DIR/vortex_shell_hw.tcl.XXXXXX")
awk -v shell="$VORTEX_HOME/hw/rtl/afu/de10pro/vortex_shell.sv" '
    /^package require -exact qsys / {
        print "package require -exact qsys 19.2"
        next
    }
    /^# vortex shell for aes test$/ {
        print "# Vortex DE10-Pro shell"
        next
    }
    /^set_module_property DESCRIPTION / {
        print "set_module_property DESCRIPTION \"Vortex DE10-Pro shell\""
        next
    }
    /^add_fileset_file vortex_shell[.]sv SYSTEM_VERILOG PATH / {
        print "add_fileset_file vortex_shell.sv SYSTEM_VERILOG PATH {" shell "} TOP_LEVEL_FILE"
        next
    }
    { print }
' "$PROJECT_DIR/vortex_shell_hw.tcl" > "$TCL_TMP"
mv "$TCL_TMP" "$PROJECT_DIR/vortex_shell_hw.tcl"

while IFS= read -r cached_shell; do
    cp "$VORTEX_HOME/hw/rtl/afu/de10pro/vortex_shell.sv" "$cached_shell"
done < <(find "$PROJECT_DIR" -type f \
    -path '*/vortex_shell_*/synth/vortex_shell.sv' -print)

if grep -Eiq 'myvortex/hw|aes test|EXT_(AES|SHA|KECCAK|GHASH|CHACHA|POLY1305)' \
    "$PROJECT_DIR/DE10_Pro.qsf" "$PROJECT_DIR/vortex_shell_hw.tcl"; then
    echo "error: legacy Vortex or crypto assignment/description remains in prepared project" >&2
    exit 1
fi

for macro in \
    'VX_CFG_XLEN=32' \
    'VX_CFG_NUM_CLUSTERS=1' \
    'VX_CFG_NUM_CORES=1' \
    "VX_CFG_NUM_WARPS=$NUM_WARPS" \
    "VX_CFG_NUM_THREADS=$NUM_THREADS" \
    'VX_CFG_EXT_F_DISABLE=1' \
    'VX_CFG_EXT_D_DISABLE=1' \
    'VX_CFG_PLATFORM_MEMORY_NUM_BANKS=1' \
    'VX_CFG_PLATFORM_MEMORY_INTERLEAVE=0'; do
    if ! grep -Fq "VERILOG_MACRO \"$macro\"" "$QSF_FRAGMENT"; then
        echo "error: missing generated macro: $macro" >&2
        exit 1
    fi
done

git -C "$VORTEX_HOME" rev-parse HEAD > "$GENERATED_DIR/VORTEX_SOURCE_REVISION"

echo "Prepared: $PROJECT_DIR"
echo "Profile: 1 core, $NUM_WARPS warp(s), $NUM_THREADS thread(s)"
echo "Source fragment: $QSF_FRAGMENT"
echo "Quartus was not invoked."
