#!/usr/bin/env bash

# Integrate vortexCrypto into the existing Gen3x16 + four-DDR4 Quartus
# baseline. This script regenerates Qsys output, but does not compile Quartus
# or program the board.
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
VORTEX_HOME=$(realpath "$SCRIPT_DIR/../../../..")
PROJECT_DIR=${VX_DE10PRO_PROJECT_DIR:-$VORTEX_HOME/../fpga_proj/PCIE_DDR4_Vortex_G3X16}
QUARTUS_ROOT=${QUARTUS_ROOT:-/data/Quartus/tools/19.2/quartus}
PROJECT_NAME=vortex_g3x16_ddr4x4
SYSTEM_NAME=pcie_ddr4_system
NUM_WARPS=${VX_DE10PRO_NUM_WARPS:-1}
NUM_THREADS=${VX_DE10PRO_NUM_THREADS:-1}

if [[ ! "$NUM_WARPS" =~ ^[1-9][0-9]*$ \
   || ! "$NUM_THREADS" =~ ^[1-9][0-9]*$ ]]; then
    echo "error: warp/thread counts must be positive integers" >&2
    exit 1
fi

if [[ ! -d "$PROJECT_DIR" ]]; then
    echo "error: FPGA project directory does not exist: $PROJECT_DIR" >&2
    exit 1
fi
PROJECT_DIR=$(realpath "$PROJECT_DIR")

PROJECT_QSF=$PROJECT_DIR/$PROJECT_NAME.qsf
SYSTEM_FILE=$PROJECT_DIR/$SYSTEM_NAME.qsys
QSYS_SCRIPT=$QUARTUS_ROOT/sopc_builder/bin/qsys-script
QSYS_GENERATE=$QUARTUS_ROOT/sopc_builder/bin/qsys-generate
COMPONENT_TEMPLATE=$SCRIPT_DIR/vortex_shell_hw.tcl.in
INTEGRATION_SCRIPT=$SCRIPT_DIR/integrate_vortex.tcl
VORTEX_SHELL=$VORTEX_HOME/hw/rtl/afu/de10pro/vortex_shell.sv

for required_file in \
    "$PROJECT_QSF" \
    "$SYSTEM_FILE" \
    "$COMPONENT_TEMPLATE" \
    "$INTEGRATION_SCRIPT" \
    "$VORTEX_HOME/VX_config.toml" \
    "$VORTEX_HOME/VX_types.toml" \
    "$VORTEX_SHELL"; do
    if [[ ! -f "$required_file" ]]; then
        echo "error: required file is missing: $required_file" >&2
        exit 1
    fi
done

for required_tool in "$QSYS_SCRIPT" "$QSYS_GENERATE"; do
    if [[ ! -x "$required_tool" ]]; then
        echo "error: required Quartus tool is missing: $required_tool" >&2
        exit 1
    fi
done

GENERATED_DIR=$PROJECT_DIR/generated/vortexcrypto
CONFIG_DIR=$GENERATED_DIR/config
FILELIST=$GENERATED_DIR/sources.f
QSF_FRAGMENT=$GENERATED_DIR/vortex_sources.qsf
COMPONENT_FILE=$PROJECT_DIR/vortex_shell_hw.tcl
CUSTOM_IP=$PROJECT_DIR/ip/pcie_ddr4_system/pcie_ddr4_system_vortex_shell_0.ip
mkdir -p "$CONFIG_DIR"

CONFIG_FLAGS="-DSYNTHESIS=1 -DQUARTUS=1 -DNDEBUG=1 -DVX_CFG_XLEN=32 -DVX_CFG_XLEN_32=1 -DVX_CFG_NUM_CLUSTERS=1 -DVX_CFG_NUM_CORES=1 -DVX_CFG_NUM_WARPS=$NUM_WARPS -DVX_CFG_NUM_THREADS=$NUM_THREADS -DVX_CFG_EXT_F_DISABLE=1 -DVX_CFG_EXT_D_DISABLE=1 -DVX_CFG_ICACHE_LATENCY=3 -DVX_CFG_DCACHE_LATENCY=3 -DVX_CFG_PLATFORM_MEMORY_NUM_BANKS=1 -DVX_CFG_PLATFORM_MEMORY_INTERLEAVE=0 -DVX_CFG_PLATFORM_CLOCK_RATE=250"

XLEN=32 python3 "$VORTEX_HOME/ci/gen_config.py" \
    --config "$VORTEX_HOME/VX_config.toml" \
    --cflags "$CONFIG_FLAGS" \
    --format verilog \
    --output "$CONFIG_DIR/VX_config.vh"

XLEN=32 python3 "$VORTEX_HOME/ci/gen_config.py" \
    --config "$VORTEX_HOME/VX_types.toml" \
    --cflags "$CONFIG_FLAGS" \
    --format verilog \
    --resolved \
    --output "$CONFIG_DIR/VX_types.vh"

"$VORTEX_HOME/hw/scripts/gen_sources.sh" \
    -DSYNTHESIS=1 \
    -DQUARTUS=1 \
    -DNDEBUG=1 \
    -DVX_CFG_XLEN=32 \
    -DVX_CFG_XLEN_32=1 \
    -DVX_CFG_NUM_CLUSTERS=1 \
    -DVX_CFG_NUM_CORES=1 \
    -DVX_CFG_NUM_WARPS="$NUM_WARPS" \
    -DVX_CFG_NUM_THREADS="$NUM_THREADS" \
    -DVX_CFG_EXT_F_DISABLE=1 \
    -DVX_CFG_EXT_D_DISABLE=1 \
    -DVX_CFG_ICACHE_LATENCY=3 \
    -DVX_CFG_DCACHE_LATENCY=3 \
    -DVX_CFG_PLATFORM_MEMORY_NUM_BANKS=1 \
    -DVX_CFG_PLATFORM_MEMORY_INTERLEAVE=0 \
    -DVX_CFG_PLATFORM_CLOCK_RATE=250 \
    -I"$CONFIG_DIR" \
    -I"$VORTEX_HOME/hw/rtl" \
    -I"$VORTEX_HOME/hw/rtl/libs" \
    -I"$VORTEX_HOME/hw/rtl/interfaces" \
    -I"$VORTEX_HOME/hw/rtl/fpu" \
    -I"$VORTEX_HOME/hw/rtl/core" \
    -I"$VORTEX_HOME/hw/rtl/mem" \
    -I"$VORTEX_HOME/hw/rtl/cache" \
    -I"$VORTEX_HOME/hw/rtl/afu/de10pro" \
    -O"$FILELIST"

{
    echo "# Generated by vortexCrypto/hw/syn/altera/de10pro/prepare_project.sh"
    while IFS= read -r entry; do
        case "$entry" in
            +define+*)
                printf 'set_global_assignment -name VERILOG_MACRO "%s"\n' "${entry#+define+}"
                ;;
            +incdir+*)
                printf 'set_global_assignment -name SEARCH_PATH "%s"\n' "${entry#+incdir+}"
                ;;
            */hw/rtl/afu/de10pro/vortex_shell.sv)
                ;;
            *.sv)
                printf 'set_global_assignment -name SYSTEMVERILOG_FILE "%s"\n' "$entry"
                ;;
            *.v)
                printf 'set_global_assignment -name VERILOG_FILE "%s"\n' "$entry"
                ;;
            '')
                ;;
            *)
                echo "error: unsupported source-list entry: $entry" >&2
                exit 1
                ;;
        esac
    done < "$FILELIST"
} > "$QSF_FRAGMENT"

awk -v shell="$VORTEX_SHELL" '
    { gsub(/@VORTEX_SHELL@/, shell); print }
' "$COMPONENT_TEMPLATE" > "$COMPONENT_FILE"

if ! grep -Fq 'source generated/vortexcrypto/vortex_sources.qsf' "$PROJECT_QSF"; then
    echo "error: $PROJECT_QSF does not source the generated Vortex assignments" >&2
    exit 1
fi

for macro in \
    'VX_CFG_XLEN=32' \
    'VX_CFG_NUM_CLUSTERS=1' \
    'VX_CFG_NUM_CORES=1' \
    "VX_CFG_NUM_WARPS=$NUM_WARPS" \
    "VX_CFG_NUM_THREADS=$NUM_THREADS" \
    'VX_CFG_EXT_F_DISABLE=1' \
    'VX_CFG_EXT_D_DISABLE=1' \
    'VX_CFG_ICACHE_LATENCY=3' \
    'VX_CFG_DCACHE_LATENCY=3' \
    'VX_CFG_PLATFORM_MEMORY_NUM_BANKS=1' \
    'VX_CFG_PLATFORM_MEMORY_INTERLEAVE=0' \
    'VX_CFG_PLATFORM_CLOCK_RATE=250'; do
    if ! grep -Fq "VERILOG_MACRO \"$macro\"" "$QSF_FRAGMENT"; then
        echo "error: missing generated macro: $macro" >&2
        exit 1
    fi
done

SEARCH_PATH="$PROJECT_DIR,\$"
"$QSYS_SCRIPT" \
    --quartus-project="$PROJECT_DIR/$PROJECT_NAME" \
    --rev="$PROJECT_NAME" \
    --system-file="$SYSTEM_FILE" \
    --search-path="$SEARCH_PATH" \
    --script="$INTEGRATION_SCRIPT"

"$QSYS_GENERATE" "$SYSTEM_FILE" \
    --synthesis=VERILOG \
    --quartus-project="$PROJECT_DIR/$PROJECT_NAME" \
    --rev="$PROJECT_NAME" \
    --search-path="$SEARCH_PATH"

CUSTOM_IP_ASSIGNMENT="set_global_assignment -name IP_FILE ip/pcie_ddr4_system/pcie_ddr4_system_vortex_shell_0.ip"
QSYS_ASSIGNMENT="set_global_assignment -name QSYS_FILE pcie_ddr4_system.qsys"
for assignment in "$CUSTOM_IP_ASSIGNMENT" "$QSYS_ASSIGNMENT"; do
    if [[ $(grep -Fxc "$assignment" "$PROJECT_QSF") -ne 1 ]]; then
        echo "error: expected exactly one QSF assignment: $assignment" >&2
        exit 1
    fi
done
if [[ ! -f "$CUSTOM_IP" ]]; then
    echo "error: generated Vortex child IP is missing: $CUSTOM_IP" >&2
    exit 1
fi
if grep -Fq 'QIP_FILE pcie_ddr4_system/pcie_ddr4_system.qip' "$PROJECT_QSF"; then
    echo "error: generated QIP and QSYS source mechanisms must not be mixed" >&2
    exit 1
fi

git -C "$VORTEX_HOME" describe --always --dirty \
    > "$GENERATED_DIR/VORTEX_SOURCE_REVISION"

echo "Prepared: $PROJECT_DIR"
echo "Profile: RV32, 1 core, $NUM_WARPS warp(s), $NUM_THREADS thread(s), DDR4A"
echo "Control window: BAR0 + 0x1000"
echo "Source fragment: $QSF_FRAGMENT"
echo "Quartus compilation and board programming were not invoked."
